[project]
name = "jpig"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
    "pyside6>=6.9.0",
    "scipy>=1.15.3",
]

[tool.uv.workspace]
members = [
    "bla",
]
